### ISSUE TITLE
Crash report when opening ME terminal

### ISSUE THREAD

**Issue by Niphemy** [Nomifactory/ExtendedCrafting#35]
I recently installed AE2 fluid crafting rework 2.5.11 v for nomi 1.7.4a. Opening the ME crafting terminal no longer works and fails to bring up and GUI. 

[crash-2024-05-01_10.54.03-server.txt](https://github.com/Nomifactory/ExtendedCrafting/files/15176097/crash-2024-05-01_10.54.03-server.txt)

**Comment by Exaxxion** [comment]
Your crash is entirely unrelated to this project.

You should report this to [AE2FCR](https://github.com/AE2-UEL/AE2FluidCraft-Rework).

**Comment by Niphemy** [comment]
My fault. I only posted it here because the crash report told me to but good to know.

**Comment by Exaxxion** [comment]
The disclaimer in the crash log is there so that people report issues with this mod to this repository rather than to the original project we forked from. Sorry for any confusion on that point.
